version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - db_volume:/app/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=temelioproj.settings

  worker:
    build: .
    command: python manage.py process_tasks
    volumes:
      - .:/app
      - db_volume:/app/db
    environment:
      - DJANGO_SETTINGS_MODULE=temelioproj.settings

volumes:
  db_volume: